### ISSUE TITLE
[Feature] Other connection (without Redis and Socket)

### ISSUE THREAD

**Issue by Lennord** [efekurbann/sync-commands#2]
Hello, it would be possible to connect the servers for commands without Socket or Redis like other plugins that do, I think it would be good for those who can't use Socket or Redis.

For example, just use the "/sync" command without going through DataBase, Socket or Redis...

Thank you for your understanding !

**Comment by efekurbann** [comment]
Hey, what do you suggest?

**Comment by Lennord** [comment]
> Hey, what do you suggest?

I propose that we can do any command enter server with bungeecord or without bungeecord but there is no need for Socket or Redis, that is to say without doing anything.

for example, do the command "/sync Hub02 /stop" at the console of the Hub01 server and which allows you to stop the Hub02 server

**Comment by efekurbann** [comment]
/sync or /bsync command already has that feature. You can specify the server in command.

/sync ServerName stop
I am not sure if that is the thing you want but that already exists.

See:
- https://github.com/efekurbann/sync-commands/blob/main/SyncCommands-bungeecord/src/main/java/xyz/efekurbann/synccommands/command/BSyncCommand.java#L41
- https://github.com/efekurbann/sync-commands/blob/main/SyncCommands-spigot/src/main/java/xyz/efekurbann/synccommands/command/SyncCommand.java#L39

**Comment by Lennord** [comment]
> /sync or /bsync command already has that feature. You can specify the server in command.
> 
> /sync ServerName stop I am not sure if that is the thing you want but that already exists.
> 
> See:
> 
> * https://github.com/efekurbann/sync-commands/blob/main/SyncCommands-bungeecord/src/main/java/xyz/efekurbann/synccommands/command/BSyncCommand.java#L41
> * https://github.com/efekurbann/sync-commands/blob/main/SyncCommands-spigot/src/main/java/xyz/efekurbann/synccommands/command/SyncCommand.java#L39

ok but you need socket or redis but that I don't want.

**Comment by efekurbann** [comment]
I see. But doesnt seem possible without plugin messaging. I do not have plans to add plugin messaging soon. 
You have to install the plugin on every server for now.

**Comment by Lennord** [comment]
> I see. But doesnt seem possible without plugin messaging. I do not have plans to add plugin messaging soon. You have to install the plugin on every server for now.

okay I understand.
Good continuation...
